### ISSUE TITLE
دریافت خطا 500 بعد از زدن دکمه 500 توی تنظیمات

### ISSUE THREAD

**Issue by amin2plus** [hiddify/hiddify-config#229]
دو تا سرور دارم روی یکیش هیچ تغییراتی نمیتونم بدم ، چون توی صفحه تنظیمات دکمه submit رو که میزنم خطا 500 میده با کد زیر:
پنل همه قسمت هاش کار میکنه ، یوزر داره و باقی صفحه ها هم میشه تغییرات داد فقط توی صفحه تنظیمات این مشکل هست
گزینه reinstall و apply configsهم میزنم همچنان مشکل داره صفحه تنظیمات
اگر راهنمایی کنید ممنون میشم
>`name 'ValidationError' is not defined
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/usr/local/lib/python3.10/dist-packages/flask_classful.py", line 268, in proxy
    response = view(**request.view_args)
  File "/usr/local/lib/python3.10/dist-packages/flask_classful.py", line 239, in inner
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/hiddifypanel/panel/admin/SettingAdmin.py", line 38, in post
    if form.validate_on_submit():
  File "/usr/local/lib/python3.10/dist-packages/flask_wtf/form.py", line 100, in validate_on_submit
    return self.is_submitted() and self.validate()
  File "/usr/local/lib/python3.10/dist-packages/wtforms/form.py", line 329, in validate
    return super().validate(extra)
  File "/usr/local/lib/python3.10/dist-packages/wtforms/form.py", line 146, in validate
    if not field.validate(self, extra):
  File "/usr/local/lib/python3.10/dist-packages/wtforms/fields/form.py", line 67, in validate
    return self.form.validate()
  File "/usr/local/lib/python3.10/dist-packages/wtforms/form.py", line 329, in validate
    return super().validate(extra)
  File "/usr/local/lib/python3.10/dist-packages/wtforms/form.py", line 146, in validate
    if not field.validate(self, extra):
  File "/usr/local/lib/python3.10/dist-packages/wtforms/fields/core.py", line 242, in validate
    stop_validation = self._run_validation_chain(form, chain)
  File "/usr/local/lib/python3.10/dist-packages/wtforms/fields/core.py", line 262, in _run_validation_chain
    validator(form, self)
  File "/usr/local/lib/python3.10/dist-packages/hiddifypanel/panel/hiddify.py", line 224, in validate_domain_exist
    raise ValidationError(_("Domain can not be resolved! there is a problem in your domain"))
NameError: name 'ValidationError' is not defined`
![image](https://user-images.githubusercontent.com/31206022/221399237-944aa460-278b-4267-a5b4-59f3457b2f40.png)

**Comment by amin2plus** [comment]
با آپدیت به [0.9.74] برطرف شد، ممنون

**Comment by MILADALEF** [comment]
چطور آپدیت کردین ؟؟ من نصب رو میزنم روی سرور جدید همین ارور رو میگیرم .

**Comment by MILADALEF** [comment]
کلا موقع ستاپ سرور جدید اصلا اجازه تعریف دامنه نمیده و مستقیم میره توی صفحه ارور ۵۰۰

**Comment by MILADALEF** [comment]
در ورژن ۷۶ اوکی شد ممنون . فقط همچنان برای ریستور بکاپ همون ارور رو داره

**Comment by arman2012** [comment]
> در ورژن ۷۶ اوکی شد ممنون . فقط همچنان برای ریستور بکاپ همون ارور رو داره

در ورژن 79 فیکس شد

**Comment by MILADALEF** [comment]
> 

متاسفانه همچنان برای ریستور ارور ۵۰۰ میده

**Comment by MILADALEF** [comment]
--: -c: line 187: conditional binary operator expected
--: -c: line 187: syntax error near `==""'
--: -c: line 187: `        if [[ $DB_VERSION =="" ]];then'


این ارور جدید هم موقع نصب !

**Comment by raminrez** [comment]
من هم الان آپدیت کردم و با این ارور روبرو شدم

**Comment by hiddify** [comment]
fixed
