### ISSUE TITLE
issue in quick set up

### ISSUE THREAD

**Issue by johnsmith1992feb** [hiddify/hiddify-config#230]
**Describe the bug**
when I enter submit in quick set up i face this error:
'NoneType' object has no attribute 'value'
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/usr/local/lib/python3.10/dist-packages/flask_classful.py", line 268, in proxy
    response = view(**request.view_args)
  File "/usr/local/lib/python3.10/dist-packages/flask_classful.py", line 239, in inner
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/hiddifypanel/panel/admin/QuickSetup.py", line 50, in post
    BoolConfig.query.filter(BoolConfig.key==ConfigEnum.firewall).first().value=quick_form.enable_firewall.data
AttributeError: 'NoneType' object has no attribute 'value'

**Comment by hiddify** [comment]
please update it has been fixed
