### ISSUE TITLE
مشکل پریدن قسمت کاربران

### ISSUE THREAD

**Issue by Obeid1375** [hiddify/hiddify-config#244]
سلام خسته نباشید. من امروز میخواستم یه کاربر رو خاموش کنم حجمشو 0 کردم و ارور 500 داد و حل شدنیم نیست.
راهنمایی کنید.

لطفا با هایدیفای از طریق آدرس ایمیل hiddify@gmail.com و ذکر مشخصات این صفحه در ارتباط باشید.

float division by zero
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/usr/local/lib/python3.10/dist-packages/flask_admin/base.py", line 69, in inner
    return self._run_view(f, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/flask_admin/base.py", line 368, in _run_view
    return fn(self, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/flask_admin/model/base.py", line 2017, in index_view
    return self.render(
  File "/usr/local/lib/python3.10/dist-packages/flask_admin/base.py", line 308, in render
    return render_template(template, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/flask/templating.py", line 154, in render_template
    return _render(
  File "/usr/local/lib/python3.10/dist-packages/flask/templating.py", line 128, in _render
    rv = template.render(context)
  File "/usr/local/lib/python3.10/dist-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/usr/local/lib/python3.10/dist-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/usr/local/lib/python3.10/dist-packages/hiddifypanel/panel/admin/templates/model/user_list.html", line 1, in top-level template code
    {% extends 'hiddify-flask-admin/list.html' %}
  File "/usr/local/lib/python3.10/dist-packages/hiddifypanel/templates/hiddify-flask-admin/list.html", line 6, in top-level template code
    {% import 'flask-admin/model/row_actions.html' as row_actions with context %}
  File "/usr/local/lib/python3.10/dist-packages/flask_adminlte3/templates/flask-admin/master.html", line 1, in top-level template code
    {% extends admin_base_template %}
  File "/usr/local/lib/python3.10/dist-packages/hiddifypanel/templates/flaskadmin-layout.html", line 1, in top-level template code
    {% extends 'admin-layout.html' %}
  File "/usr/local/lib/python3.10/dist-packages/hiddifypanel/templates/admin-layout.html", line 2, in top-level template code
    {% from 'macros.html' import icon,render_nav_item %}
  File "/usr/local/lib/python3.10/dist-packages/hiddifypanel/templates/master.html", line 46, in top-level template code
    {% block page_body %}
  File "/usr/local/lib/python3.10/dist-packages/hiddifypanel/templates/master.html", line 78, in block 'page_body'
    {% block body %}{% endblock %}
  File "/usr/local/lib/python3.10/dist-packages/hiddifypanel/panel/admin/templates/model/user_list.html", line 4, in block 'body'
    {{super()}}
  File "/usr/local/lib/python3.10/dist-packages/hiddifypanel/templates/hiddify-flask-admin/list.html", line 78, in block 'body'
    {% block model_list_table %}
  File "/usr/local/lib/python3.10/dist-packages/hiddifypanel/templates/hiddify-flask-admin/list.html", line 129, in block 'model_list_table'
    {% block list_row scoped %}
  File "/usr/local/lib/python3.10/dist-packages/hiddifypanel/templates/hiddify-flask-admin/list.html", line 158, in block 'list_row'
    {{ get_value(row, c) }}
  File "/usr/local/lib/python3.10/dist-packages/flask_admin/model/base.py", line 1865, in get_list_value
    return self._get_list_value(
  File "/usr/local/lib/python3.10/dist-packages/flask_admin/model/base.py", line 1835, in _get_list_value
    value = column_fmt(self, context, model, name)
  File "/usr/local/lib/python3.10/dist-packages/hiddifypanel/panel/admin/UserAdmin.py", line 112, in _usage_formatter
    rate=round(u*100/t)
ZeroDivisionError: float division by zero

**Comment by hiddify** [comment]
fixed
