### ISSUE TITLE
ارور موقع restore 

### ISSUE THREAD

**Issue by sirvan1133** [hiddify/hiddify-config#250]
من موقع restore 
این ارور رو دارم 
ممنون میشم راهنمایی کنید

'mode'
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/usr/local/lib/python3.10/dist-packages/flask_classful.py", line 268, in proxy
    response = view(**request.view_args)
  File "/usr/local/lib/python3.10/dist-packages/flask_classful.py", line 239, in inner
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/hiddifypanel/panel/admin/Backup.py", line 39, in post
    hiddify.set_db_from_json(json_data,
  File "/usr/local/lib/python3.10/dist-packages/hiddifypanel/panel/hiddify.py", line 338, in set_db_from_json
    dbuser.mode=user['mode']
KeyError: 'mode'

**Comment by hiddify** [comment]
fixed

ولی آپدیته خیلی قدیمی بوده
