### ISSUE TITLE
[BUG] Can't access user's page/configs with direct IP

### ISSUE THREAD

**Issue by mozilla-firefox** [hiddify/hiddify-config#299]
سلام
من آخرین نسخه پنل پنل (7.1.2) رو نصب کردم، دامنه اد کردم، یوزر جدید ساختم
از طریق دامنه میتونم به پیج کاربر یا کانفیگ هاش دسترسی داشته باشم
https://domain_name/base_path/uuid/ >> OK
اما از طریق آی پی برام ممکن نیست
http://ip_address/base_path/uuid/ >> error 500
https://ip_address/base_path/uuid/ >> error 500
```
500
 Oops! Something went wrong.
Please contact hiddify@gmail.com with the details in this page.

<ConfigEnum.proxy_path: 'proxy_path'>
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/usr/local/lib/python3.10/dist-packages/flask_classful.py", line 268, in proxy
    response = view(**request.view_args)
  File "/usr/local/lib/python3.10/dist-packages/flask_classful.py", line 239, in inner
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/hiddifypanel/panel/user/user.py", line 24, in index
    return render_template('home/index.html',**c,ua=user_agent)
  File "/usr/local/lib/python3.10/dist-packages/flask/templating.py", line 154, in render_template
    return _render(
  File "/usr/local/lib/python3.10/dist-packages/flask/templating.py", line 128, in _render
    rv = template.render(context)
  File "/usr/local/lib/python3.10/dist-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/usr/local/lib/python3.10/dist-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/usr/local/lib/python3.10/dist-packages/hiddifypanel/panel/user/templates/home/index.html", line 1, in top-level template code
    {% extends "master.html" %}
  File "/usr/local/lib/python3.10/dist-packages/hiddifypanel/templates/master.html", line 46, in top-level template code
    {% block page_body %}
  File "/usr/local/lib/python3.10/dist-packages/hiddifypanel/templates/master.html", line 78, in block 'page_body'
    {% block body %}{% endblock %}
  File "/usr/local/lib/python3.10/dist-packages/hiddifypanel/panel/user/templates/home/index.html", line 63, in block 'body'
    {% include 'home/ios.html' %}
  File "/usr/local/lib/python3.10/dist-packages/hiddifypanel/panel/user/templates/home/ios.html", line 33, in top-level template code
    {% set pinfo=link_maker.make_proxy(type,d) %}
  File "/usr/local/lib/python3.10/dist-packages/hiddifypanel/panel/user/link_maker.py", line 103, in make_proxy
    ws_path={'vless':f'/{hconfigs[ConfigEnum.proxy_path]}/vlessws',
KeyError: <ConfigEnum.proxy_path: 'proxy_path'>
```
البته دسترسی به پنل ادمین از طریق آی پی مشکلی نداره

**Comment by lymanjre** [comment]
آپدیت جدید را چک کنید لطفا. مشکی نداره
