### ISSUE TITLE
hiddify-v10.1.0 and hiddify-panel 7.1.1 bug - Can't load users or domain page

### ISSUE THREAD

**Issue by just1random** [hiddify/hiddify-config#3051]
It throws error 500

```unsupported format character 'D' (0x44) at index 170
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/usr/local/lib/python3.8/dist-packages/flask_admin/base.py", line 69, in inner
    return self._run_view(f, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/flask_admin/base.py", line 368, in _run_view
    return fn(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/flask_admin/model/base.py", line 2017, in index_view
    return self.render(
  File "/usr/local/lib/python3.8/dist-packages/flask_admin/base.py", line 308, in render
    return render_template(template, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/flask/templating.py", line 154, in render_template
    return _render(
  File "/usr/local/lib/python3.8/dist-packages/flask/templating.py", line 128, in _render
    rv = template.render(context)
  File "/usr/local/lib/python3.8/dist-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/usr/local/lib/python3.8/dist-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/usr/local/lib/python3.8/dist-packages/hiddifypanel/panel/admin/templates/model/user_list.html", line 1, in top-level template code
    {% extends 'hiddify-flask-admin/list.html' %}
  File "/usr/local/lib/python3.8/dist-packages/hiddifypanel/templates/hiddify-flask-admin/list.html", line 6, in top-level template code
    {% import 'flask-admin/model/row_actions.html' as row_actions with context %}
  File "/usr/local/lib/python3.8/dist-packages/flask_adminlte3/templates/flask-admin/master.html", line 1, in top-level template code
    {% extends admin_base_template %}
  File "/usr/local/lib/python3.8/dist-packages/hiddifypanel/templates/flaskadmin-layout.html", line 1, in top-level template code
    {% extends 'admin-layout.html' %}
  File "/usr/local/lib/python3.8/dist-packages/hiddifypanel/templates/admin-layout.html", line 2, in top-level template code
    {% from 'macros.html' import icon,render_nav_item %}
  File "/usr/local/lib/python3.8/dist-packages/hiddifypanel/templates/master.html", line 179, in top-level template code
    {% block tail_js %}
  File "/usr/local/lib/python3.8/dist-packages/hiddifypanel/panel/admin/templates/model/user_list.html", line 59, in block 'tail_js'
    {{super()}}
  File "/usr/local/lib/python3.8/dist-packages/hiddifypanel/templates/flaskadmin-layout.html", line 120, in block 'tail_js'
    $("#servernames").parent().find(".help-block").html(`{{_('domain.domain_fronting.description')}}`)
  File "/usr/local/lib/python3.8/dist-packages/jinja2/ext.py", line 167, in _gettext_alias
    return __context.call(__context.resolve("gettext"), *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/jinja2/ext.py", line 179, in gettext
    return rv % variables  # type: ignore
ValueError: unsupported format character 'D' (0x44) at index 170```

**Comment by vahidsrlk** [comment]
آپدیت کنید به 7.1.2 مشکل حل شد
ممنون از تیم هیدیفای

**Comment by just1random** [comment]
Great work as always.
Issue resolved.
Thank you.
