### ISSUE TITLE
مشکل عدم نمایش قسمت پنل کاربر 

### ISSUE THREAD

**Issue by Noface68** [hiddify/hiddify-config#3211]
500
خطایی رخ داده است!! Hiddify Panel 8.0.0.dev41
لطفا با هیدیفای از طریق آدرس ایمیل info@hiddify.com و ذکر مشخصات این صفحه در ارتباط باشید.

        
'encryption'
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/usr/local/lib/python3.10/dist-packages/flask_classful.py", line 268, in proxy
    response = view(**request.view_args)
  File "/usr/local/lib/python3.10/dist-packages/flask_classful.py", line 239, in inner
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/hiddifypanel/panel/user/user.py", line 62, in new
    return render_template('home/multi.html', **c, ua=user_agent)
  File "/usr/local/lib/python3.10/dist-packages/flask/templating.py", line 154, in render_template
    return _render(
  File "/usr/local/lib/python3.10/dist-packages/flask/templating.py", line 128, in _render
    rv = template.render(context)
  File "/usr/local/lib/python3.10/dist-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/usr/local/lib/python3.10/dist-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/usr/local/lib/python3.10/dist-packages/hiddifypanel/panel/user/templates/home/multi.html", line 3, in top-level template code
    {% from 'macros.html' import modal %}
  File "/usr/local/lib/python3.10/dist-packages/hiddifypanel/templates/master.html", line 76, in top-level template code
    {% block page_body %}
  File "/usr/local/lib/python3.10/dist-packages/hiddifypanel/templates/master.html", line 108, in block 'page_body'
    {% block body %}{% endblock %}
  File "/usr/local/lib/python3.10/dist-packages/hiddifypanel/panel/user/templates/home/multi.html", line 113, in block 'body'
    {% include 'home/all-configs.html'%}
  File "/usr/local/lib/python3.10/dist-packages/hiddifypanel/panel/user/templates/home/all-configs.html", line 107, in top-level template code
    <div class="btn-group"><a href='{{link_maker.to_link(pinfo)}}' class="btn btn-light orig-link">{{pinfo["name"].replace("_", " ")}}</a></div>
  File "/usr/local/lib/python3.10/dist-packages/hiddifypanel/panel/user/link_maker.py", line 259, in to_link
    baseurl = f'ss://{proxy["encryption"]}:{proxy["uuid"]}@{proxy["server"]}:{proxy["port"]}'
KeyError: 'encryption'

                    
![Screenshot_20230820_074535](https://github.com/hiddify/hiddify-config/assets/142715151/a9ac80b3-e4a6-4d88-947f-0a3c8cffd0e0)

**Comment by hiddify-com** [comment]
Thank you for your contribution. However, due to many similar or old issues, this bot automatically closed the issue. Please open a new issue if the problem is still there.

این یک پیام خودکار است.
به علت شباهت های بسایری که بین ایشو ها بود و خیلی هاش رفع شده
برای مدیریت بهتر به صورت خودکار تمام ایشو ها بسته میشه

ولی خواهشمند است که در صورتی که همچنان مشکل شما وجود دارد و یا نیاز به بهبود هست به ما پیام بدید

تا بتونیم مدیریت بهتری روی ایشو ها داشته باشیم.

با سپاس
