### ISSUE TITLE
module 'lib' has no attribute 'X509_V_FLAG_CB_ISSUER_CHECK'

### ISSUE THREAD

**Issue by ShayanGsh** [hiddify/hiddify-config#3229]
**Describe the bug**
The web-ui panel does not load, and instead it's showing "Internal Server Error"

**Additional context**
Running restart, reinstall, and update commands result in an exception

Here's the stacktrace:

`Original exception was:
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 185, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.8/runpy.py", line 144, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/usr/lib/python3.8/runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "/usr/local/lib/python3.8/dist-packages/hiddifypanel/__init__.py", line 3, in <module>
    from .base import create_app, create_app_wsgi
  File "/usr/local/lib/python3.8/dist-packages/hiddifypanel/base.py", line 6, in <module>
    from hiddifypanel.panel.init_db import init_db
  File "/usr/local/lib/python3.8/dist-packages/hiddifypanel/panel/__init__.py", line 1, in <module>
    from . import user
  File "/usr/local/lib/python3.8/dist-packages/hiddifypanel/panel/user/__init__.py", line 1, in <module>
    from .user import UserView
  File "/usr/local/lib/python3.8/dist-packages/hiddifypanel/panel/user/user.py", line 9, in <module>
    from hiddifypanel.panel import hiddify, clean_ip
  File "/usr/local/lib/python3.8/dist-packages/hiddifypanel/panel/hiddify.py", line 17, in <module>
    import requests
  File "/usr/lib/python3/dist-packages/requests/__init__.py", line 95, in <module>
    from urllib3.contrib import pyopenssl
  File "/usr/lib/python3/dist-packages/urllib3/contrib/pyopenssl.py", line 46, in <module>
    import OpenSSL.SSL
  File "/usr/lib/python3/dist-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import crypto, SSL
  File "/usr/lib/python3/dist-packages/OpenSSL/crypto.py", line 1553, in <module>
    class X509StoreFlags(object):
  File "/usr/lib/python3/dist-packages/OpenSSL/crypto.py", line 1573, in X509StoreFlags
    CB_ISSUER_CHECK = _lib.X509_V_FLAG_CB_ISSUER_CHECK
AttributeError: module 'lib' has no attribute 'X509_V_FLAG_CB_ISSUER_CHECK'`

I have already found a [possible fix](https://stackoverflow.com/questions/73830524/attributeerror-module-lib-has-no-attribute-x509-v-flag-cb-issuer-check) but since the server is being entirely managed by Hiddify, I decided not to touch anything

**Comment by ShayanGsh** [comment]
**Update**

I ran `pip install pyopenssl --upgrade` (without upgrading `pip` first or commenting that line)
But that did not change anything, so I restarted the VPS through command line by running `reboot`
After the reboot, the panel loaded up fine, and all of the services were `active` except xray

Xray was stuck on `activating`, and the only thing that fixed it was reinstalling hiddify-config through command panel.

The server looks to be operating fine at the moment, I had not ssh-ed into the server for a long time so whatever caused that error was probably a bug in hiddify-config.

I'd keep this issue open in case it provides helpful information to the devs. They can close it whenever they deem it necessary, since my problem is fixed now.

I must also mention that while the panel didn't load up, all the services were working fine anyways, and their status was on `active`

**Comment by hiddify-com** [comment]
Thank you for your contribution. However, due to many similar or old issues, this bot automatically closed the issue. Please open a new issue if the problem is still there.

این یک پیام خودکار است.
به علت شباهت های بسایری که بین ایشو ها بود و خیلی هاش رفع شده
برای مدیریت بهتر به صورت خودکار تمام ایشو ها بسته میشه

ولی خواهشمند است که در صورتی که همچنان مشکل شما وجود دارد و یا نیاز به بهبود هست به ما پیام بدید

تا بتونیم مدیریت بهتری روی ایشو ها داشته باشیم.

با سپاس
