### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by UltimateABC** [hiddify/hiddify-config#3235]
Hi

i get "**Internal Server Error**" text error when i trying to open the admin panel or any link related to hiddify panel since latest update has installed .

**Comment by UltimateABC** [comment]
when i trying to get new admin links in hiddify cli command, i got this error:

```
Hiddify: Command admin
==========================================
Caching Error! Disabling cache Error 111 connecting to unix socket: /opt/hiddify-config/other/redis/run.sock. Connection refused.
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/engine/base.py", line 1900, in _execute_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: no such column: user.usage_limit

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.10/dist-packages/hiddifypanel/__main__.py", line 13, in <module>
    main()
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/flask/cli.py", line 567, in main
    return super().main(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1651, in invoke
    cmd_name, cmd, args = self.resolve_command(ctx, args)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1698, in resolve_command
    cmd = self.get_command(ctx, cmd_name)
  File "/usr/local/lib/python3.10/dist-packages/flask/cli.py", line 523, in get_command
    return info.load_app().cli.get_command(ctx, name)
  File "/usr/local/lib/python3.10/dist-packages/flask/cli.py", line 362, in load_app
    app = self.create_app()
  File "/usr/local/lib/python3.10/dist-packages/hiddifypanel/base.py", line 84, in create_app_wsgi
    app = create_app()
  File "/usr/local/lib/python3.10/dist-packages/hiddifypanel/base.py", line 33, in create_app
    init_db()
  File "/usr/local/lib/python3.10/dist-packages/hiddifypanel/panel/init_db.py", line 108, in init_db
    hiddify.set_db_from_json(json_data,
  File "/usr/local/lib/python3.10/dist-packages/hiddifypanel/panel/hiddify.py", line 461, in set_db_from_json
    bulk_register_users(json_data['users'], commit=False, remove=remove_users)
  File "/usr/local/lib/python3.10/dist-packages/hiddifypanel/models/user.py", line 325, in bulk_register_users
    add_or_update_user(commit=False, **u)
  File "/usr/local/lib/python3.10/dist-packages/hiddifypanel/models/user.py", line 272, in add_or_update_user
    dbuser = User.by_uuid(user['uuid'], create=True)
  File "/usr/local/lib/python3.10/dist-packages/hiddifypanel/models/user.py", line 120, in by_uuid
    dbuser = User.query.filter_by(uuid=user_uuid).first()
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/orm/query.py", line 2824, in first
    return self.limit(1)._iter().first()
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/orm/query.py", line 2916, in _iter
    result = self.session.execute(
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/orm/session.py", line 1714, in execute
    result = conn._execute_20(statement, params or {}, execution_options)
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/engine/base.py", line 1705, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/sql/elements.py", line 334, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/engine/base.py", line 1572, in _execute_clauseelement
    ret = self._execute_context(
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/engine/base.py", line 1943, in _execute_context
    self._handle_dbapi_exception(
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/engine/base.py", line 2124, in _handle_dbapi_exception
    util.raise_(
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/engine/base.py", line 1900, in _execute_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such column: user.usage_limit
[SQL: SELECT user.id AS user_id, user.uuid AS user_uuid, user.name AS user_name, user.last_online AS user_last_online, user.expiry_time AS user_expiry_time, user.usage_limit AS user_usage_limit, user.package_days AS user_package_days, user.mode AS user_mode, user.monthly AS user_monthly, user.start_date AS user_start_date, user.current_usage AS user_current_usage, user.last_reset_time AS user_last_reset_time, user.comment AS user_comment, user.telegram_id AS user_telegram_id, user.added_by AS user_added_by, user.max_ips AS user_max_ips, user.enable AS user_enable, user.ed25519_private_key AS user_ed25519_private_key, user.ed25519_public_key AS user_ed25519_public_key 
FROM user 
WHERE user.uuid = ?
 LIMIT ? OFFSET ?]
[parameters: ('07464df4-5c3a-4c3d-9ece-3531407b785b', 1, 0)]
(Background on this error at: https://sqlalche.me/e/14/e3q8)
Press any key to return to menu
```

**Comment by UltimateABC** [comment]
i tried to apply configs wright now, but it doesnt work anymore, no access to panel!

**Comment by UltimateABC** [comment]
```  File "/usr/local/lib/python3.10/dist-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.DataError: (1366, "Incorrect string value: '\\xF0\\x9F\\x9A\\x80SR...' for column `hiddifypanel`.`domain`.`alias` at row 1")

The above exception was the direct cause of the following exception:
```

where is the db file?

```
'\\xF0\\x9F\\x9A\\x80SR...' for column `hiddifypanel`.`domain`.`alias` at row 1"

```
how can i edit it manually?

**Comment by UltimateABC** [comment]
i edited hiddifypanel.db file and edited server names, not works too.

**Comment by hiddify-com** [comment]
Thank you for your contribution. However, due to many similar or old issues, this bot automatically closed the issue. Please open a new issue if the problem is still there.

این یک پیام خودکار است.
به علت شباهت های بسایری که بین ایشو ها بود و خیلی هاش رفع شده
برای مدیریت بهتر به صورت خودکار تمام ایشو ها بسته میشه

ولی خواهشمند است که در صورتی که همچنان مشکل شما وجود دارد و یا نیاز به بهبود هست به ما پیام بدید

تا بتونیم مدیریت بهتری روی ایشو ها داشته باشیم.

با سپاس
