### ISSUE TITLE
مشکل پنل کاربر در حالت developer و ایجاد متن نا مفهوم کنار ایجاد کاربر

### ISSUE THREAD

**Issue by Obeid1375** [hiddify/hiddify-config#336]
ارور صفحه کاربر.

`unsupported operand type(s) for -: 'NoneType' and 'datetime.date'
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/usr/local/lib/python3.10/dist-packages/flask_classful.py", line 268, in proxy
    response = view(**request.view_args)
  File "/usr/local/lib/python3.10/dist-packages/flask_classful.py", line 239, in inner
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/hiddifypanel/panel/user/user.py", line 39, in new
    c=get_common_data(g.user_uuid,mode="new")
  File "/usr/local/lib/python3.10/dist-packages/hiddifypanel/panel/user/user.py", line 162, in get_common_data
    'expire_s':int((user.expiry_time-datetime.date(1970, 1, 1)).total_seconds()),
TypeError: unsupported operand type(s) for -: 'NoneType' and 'datetime.date'`

![Uploading Screenshot 2023-03-06 201236.png…]()

**Comment by hiddify1** [comment]
اپدیت کن دوولوپ رو
