### ISSUE TITLE
ارور 500 موقع ساخت کاربر در پنل 1.4.0

### ISSUE THREAD

**Issue by Obeid1375** [hiddify/hiddify-config#344]
موقع ساخت کاربر ارور 500 داده میشه.

`'UserForm' object has no attribute 'reset'
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/usr/local/lib/python3.10/dist-packages/flask_admin/base.py", line 69, in inner
    return self._run_view(f, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/flask_admin/base.py", line 368, in _run_view
    return fn(self, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/flask_admin/model/base.py", line 2088, in create_view
    model = self.create_model(form)
  File "/usr/local/lib/python3.10/dist-packages/flask_admin/contrib/sqla/view.py", line 1165, in create_model
    if not self.handle_view_exception(ex):
  File "/usr/local/lib/python3.10/dist-packages/flask_admin/contrib/sqla/view.py", line 1133, in handle_view_exception
    return super(ModelView, self).handle_view_exception(exc)
  File "/usr/local/lib/python3.10/dist-packages/flask_admin/contrib/sqla/view.py", line 1162, in create_model
    self._on_model_change(form, model, True)
  File "/usr/local/lib/python3.10/dist-packages/flask_admin/model/base.py", line 1569, in _on_model_change
    self.on_model_change(form, model, is_created)
  File "/usr/local/lib/python3.10/dist-packages/hiddifypanel/panel/admin/UserAdmin.py", line 206, in on_model_change
    print(form.reset.__dict__)
AttributeError: 'UserForm' object has no attribute 'reset'`

**Comment by lumanjre** [comment]
چک کنید الان باید حل شده باشه
