### ISSUE TITLE
Bug: Hiddify-xray service stops by itself after few minutes

### ISSUE THREAD

**Issue by swifast** [hiddify/hiddify-config#351]
پورت ۸۰ بعد از مدتی استفاده روی سرور بسته می‌شود و فقط در صورت اجرا کردن فایل بش install یا apply_configs پورت مجدد باز می‌شود. ولی پس از گذشت حدود ۱۰ دقیقه مجدد بسته می‌شود.

**Comment by swifast** [comment]
پس از بررسی مجدد متوجه شدم سرویس hiddify-xray در اصل stop می‌شود که چنین مشکلی پیش میاد. سرویس restart نمیشود و پس از disable کردن نمیتوان آن را enable کرد.
با تشکر از زحمات همگی

**Comment by swifast** [comment]
google.golang.org/grpc@v1.53.0/server.go:963 +0x28a
created by google.golang.org/grpc.(*Server).serveStreams.func1
	google.golang.org/grpc@v1.53.0/server.go:965 +0x98
google.golang.org/grpc.(*Server).serveStreams.func1.2()
	google.golang.org/grpc@v1.53.0/server.go:1704 +0xa36
google.golang.org/grpc.(*Server).handleStream(0xc000e6e960, {0x13f6200, 0xc001c19860}, 0xc000267680, 0x0)
	google.golang.org/grpc@v1.53.0/server.go:1336 +0xd33
google.golang.org/grpc.(*Server).processUnaryRPC(0xc000e6e960, {0x13f6200, 0xc001c19860}, 0xc000267680, 0xc0001e5aa0, 0x1c1f830, 0x0)
	github.com/xtls/xray-core/app/proxyman/command/command_grpc.pb.go:185 +0x170
github.com/xtls/xray-core/app/proxyman/command._HandlerService_AlterInbound_Handler({0x1158d40?, 0xc0001e5980}, {0x13eeb40, 0xc001c6d950}, 0xc00031e310, 0x0)
	github.com/xtls/xray-core/app/proxyman/command/command.go:97 +0x2c2
github.com/xtls/xray-core/app/proxyman/command.(*handlerServer).AlterInbound(0xc0001e5980, {0x13eeb40, 0xc001c6d950}, 0xc00136e740)
	github.com/xtls/xray-core/app/proxyman/command/command.go:48 +0x177
github.com/xtls/xray-core/app/proxyman/command.(*AddUserOperation).ApplyInbound(0xc001c6db30, {0x13eeb40, 0xc001c6d950}, {0x13ef518?, 0xc0011c1480?})
	github.com/xtls/xray-core/proxy/vless/inbound/inbound.go:177 +0x25
github.com/xtls/xray-core/proxy/vless/inbound.(*Handler).AddUser(0xc00246a780?, {0x7f4bf92d1db8?, 0xc0011c1440?}, 0x5e5b8c?)
	github.com/xtls/xray-core/proxy/vless/validator.go:26 +0x209
github.com/xtls/xray-core/proxy/vless.(*Validator).Add(0xc0011c1400, 0xc001c6dce0)
goroutine 18224 [running]:

panic: interface conversion: protocol.Account is *trojan.MemoryAccount, not *vless.MemoryAccount
xctl> [ /opt/hiddify-config/xray/configs/05_inbounds_06_ss4plugin.json ] appended inbound with tag:  ss-plugin
xctl> [ /opt/hiddify-config/xray/configs/05_inbounds_05_vmess_ws_old.json ] appended inbound with tag:  vmess-ws-old
xctl> [ /opt/hiddify-config/xray/configs/05_inbounds_05_vmess_ws.json ] appended inbound with tag:  vmess-ws
xctl> [ /opt/hiddify-config/xray/configs/05_inbounds_05_vless_ws.json ] appended inbound with tag:  vless-ws
xctl> [ /opt/hiddify-config/xray/configs/05_inbounds_05_v2ray_ws_old.json ] appended inbound with tag:  v2ray-ws-old
xctl> [ /opt/hiddify-config/xray/configs/05_inbounds_05_v2ray_ws.json ] appended inbound with tag:  v2ray-ws
xctl> [ /opt/hiddify-config/xray/configs/05_inbounds_05_trojan_ws_old.json ] appended inbound with tag:  trojan-ws-old
xctl> [ /opt/hiddify-config/xray/configs/05_inbounds_05_trojan_ws.json ] appended inbound with tag:  trojan-ws
xctl> [ /opt/hiddify-config/xray/configs/05_inbounds_04_vmess_grpc.json ] appended inbound with tag:  vmess-grpc
xctl> [ /opt/hiddify-config/xray/configs/05_inbounds_04_vless_grpc.json ] appended inbound with tag:  vless-grpc
xctl> [ /opt/hiddify-config/xray/configs/05_inbounds_04_trojan_grpc.json ] appended inbound with tag:  trojan-grpc
xctl> [ /opt/hiddify-config/xray/configs/05_inbounds_04_ss_grpc.json ] appended inbound with tag:  ss-grpc
xctl> [ /opt/hiddify-config/xray/configs/05_inbounds_03_vmess.json ] appended inbound with tag:  vmess
xctl> [ /opt/hiddify-config/xray/configs/05_inbounds_03_vless.json ] appended inbound with tag:  vless
xctl> [ /opt/hiddify-config/xray/configs/05_inbounds_03_trojan.json ] appended inbound with tag:  trojan
xctl> [ /opt/hiddify-config/xray/configs/05_inbounds_03_dispatcher_h2.json ] appended inbound with tag:  dispatcher_h2
xctl> [ /opt/hiddify-config/xray/configs/05_inbounds_03_dispatcher.json ] appended inbound with tag:  dispatcher
xctl> [ /opt/hiddify-config/xray/configs/05_inbounds_02_xtls_main.json ] appended inbound with tag:  xtls
xctl> [ /opt/hiddify-config/xray/configs/05_inbounds_02_quic_main.json ] appended inbound with tag:  quic
xctl> [ /opt/hiddify-config/xray/configs/05_inbounds_02_kcp_main.json ] appended inbound with tag:  kcp
xctl> [ /opt/hiddify-config/xray/configs/05_inbounds_02_http_main.json ] appended inbound with tag:  http
2023/03/07 20:32:55 Using confdir from arg: /opt/hiddify-config/xray/configs/
