### ISSUE TITLE
500 error

### ISSUE THREAD

**Issue by jalallinux** [hiddify/hiddify-config#375]
وقتی کانفیگ کلش یا هیدیفای رو انتخاب میکنم. (لینکشونو باز میکنم)

500
خطایی رخ داده است!!
لطفا با هیدیفای از طریق آدرس ایمیل [hiddify@gmail.com](mailto:hiddify@gmail.com) و ذکر مشخصات این صفحه در ارتباط باشید.

Encountered unknown tag 'link_maker'.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/usr/local/lib/python3.8/dist-packages/flask_classful.py", line 268, in proxy
    response = view(**request.view_args)
  File "/usr/local/lib/python3.8/dist-packages/flask_classful.py", line 239, in inner
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/hiddifypanel/panel/user/user.py", line 70, in clash_config
    resp= Response(render_template('clash_config.yml',typ=typ,meta_or_normal=meta_or_normal,**c,hash=hash_rnd))
  File "/usr/local/lib/python3.8/dist-packages/flask/templating.py", line 155, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/usr/local/lib/python3.8/dist-packages/jinja2/environment.py", line 1081, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/usr/local/lib/python3.8/dist-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "/usr/local/lib/python3.8/dist-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/usr/local/lib/python3.8/dist-packages/jinja2/loaders.py", line 138, in load
    code = environment.compile(source, name, filename)
  File "/usr/local/lib/python3.8/dist-packages/jinja2/environment.py", line 768, in compile
    self.handle_exception(source=source_hint)
  File "/usr/local/lib/python3.8/dist-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/usr/local/lib/python3.8/dist-packages/hiddifypanel/panel/user/templates/clash_config.yml", line 100, in template
    {%link_maker.get_all_clash_configs(meta_or_normal,domains)%}
jinja2.exceptions.TemplateSyntaxError: Encountered unknown tag 'link_maker'.

**Comment by sh4msi** [comment]
اپدیت کن 
رو 1.6.8 این رو رفع کردن

**Comment by jalallinux** [comment]
کجا باید اپدیت کنم؟

**Comment by sh4msi** [comment]
> کجا باید اپدیت کنم؟

از منو اقدام -< بروز رسانی سیستم رو بزن

**Comment by lymanjre** [comment]
آپدیت جدید را چک کنید لطفا. مشکی نداره
