### ISSUE TITLE
#bug Add clean IP on the developer version

### ISSUE THREAD

**Issue by ExPLoSiVe1988** [hiddify/hiddify-config#388]
سلام ادمین عزیز 
بابت زحماتی که میکشی ممنونم
لطفا باگ اضافه کردن آیپی تمیز رو در نسخه دولوپر فیکس کن 
بازم ممنونم

500
خطایی رخ داده است!!

لطفا با هیدیفای از طریق آدرس ایمیل hiddify@gmail.com و ذکر مشخصات این صفحه در ارتباط باشید.

name 'model' is not defined
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/usr/local/lib/python3.8/dist-packages/flask_admin/base.py", line 69, in inner
    return self._run_view(f, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/flask_admin/base.py", line 368, in _run_view
    return fn(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/flask_admin/model/base.py", line 2142, in edit_view
    if self.update_model(form, model):
  File "/usr/local/lib/python3.8/dist-packages/flask_admin/contrib/sqla/view.py", line 1191, in update_model
    if not self.handle_view_exception(ex):
  File "/usr/local/lib/python3.8/dist-packages/flask_admin/contrib/sqla/view.py", line 1133, in handle_view_exception
    return super(ModelView, self).handle_view_exception(exc)
  File "/usr/local/lib/python3.8/dist-packages/flask_admin/contrib/sqla/view.py", line 1188, in update_model
    self._on_model_change(form, model, False)
  File "/usr/local/lib/python3.8/dist-packages/flask_admin/model/base.py", line 1569, in _on_model_change
    self.on_model_change(form, model, is_created)
  File "/usr/local/lib/python3.8/dist-packages/hiddifypanel/panel/admin/DomainAdmin.py", line 145, in on_model_change
    if not get_domain(model.domain):
  File "/usr/local/lib/python3.8/dist-packages/hiddifypanel/models/domain.py", line 52, in get_domain
    return Domain.query.filter(Domain.domain==model.domain).first()
NameError: name 'model' is not defined

**Comment by lymanjre** [comment]
آپدیت جدید را چک کنید لطفا. مشکی نداره
