### ISSUE TITLE
خطا در دسترسی به پنل و ذخیره دامین در پنل  در تنظیمات اولیه 

### ISSUE THREAD

**Issue by mightymeyti** [hiddify/hiddify-config#453]
'latin-1' codec can't encode characters in position 0-2: ordinal not in range(256)
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/usr/local/lib/python3.8/dist-packages/flask_classful.py", line 268, in proxy
    response = view(**request.view_args)
  File "/usr/local/lib/python3.8/dist-packages/flask_classful.py", line 239, in inner
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/hiddifypanel/panel/admin/Dashboard.py", line 37, in index
    flash((_('It seems that you have not created any users yet. Default user link: %(default_link)s',default_link=hiddify.get_user_link(u,d))),'secondary')
  File "/usr/local/lib/python3.8/dist-packages/hiddifypanel/panel/hiddify.py", line 226, in flash
    print(message)
UnicodeEncodeError: 'latin-1' codec can't encode characters in position 0-2: ordinal not in range(256)

**Comment by lymanjre** [comment]
آپدیت جدید را چک کنید لطفا. مشکی نداره
