### ISSUE TITLE
لینک ستاپ سریع ارور 500 میده

### ISSUE THREAD

**Issue by payanthe** [hiddify/hiddify-config#501]
مشکل نصب در اوبونتو
بعد از نصب لینک کامل کردن ستاپ این ارور رو میده

500
خطایی رخ داده است!!
لطفا با هیدیفای از طریق آدرس ایمیل hiddify@gmail.com و ذکر مشخصات این صفحه در ارتباط باشید.

'list' object has no attribute 'first'
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/usr/local/lib/python3.10/dist-packages/flask_classful.py", line 268, in proxy
    response = view(**request.view_args)
  File "/usr/local/lib/python3.10/dist-packages/flask_classful.py", line 239, in inner
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/hiddifypanel/panel/admin/QuickSetup.py", line 26, in index
    return render_template('quick_setup.html', lang_form=get_lang_form(), form=get_quick_setup_form(),ipv4=hiddify.get_ip(4),ipv6=hiddify.get_ip(6),admin_link=admin_link(),show_domain_info=True)
  File "/usr/local/lib/python3.10/dist-packages/hiddifypanel/panel/admin/QuickSetup.py", line 121, in admin_link
    return "https://"+get_panel_domains().first().domain+hiddify.get_admin_path()
AttributeError: 'list' object has no attribute 'first'

                    

 - OS: Ubuntu 22.04

**Comment by lymanjre** [comment]
آپدیت جدید را چک کنید لطفا. مشکی نداره
