### ISSUE TITLE
ارور 500 در صفحه کاربران

### ISSUE THREAD

**Issue by dfjavan** [hiddify/hiddify-config#537]
**سلام از صبح با ارور 500 در صفحه کاربران روبروشدم**

500
خطایی رخ داده است!! Hiddify Panel 2.7.3
لطفا با هیدیفای از طریق آدرس ایمیل hiddify@gmail.com و ذکر مشخصات این صفحه در ارتباط باشید.

'str' object has no attribute 'get'
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/usr/local/lib/python3.8/dist-packages/flask_classful.py", line 268, in proxy
    response = view(**request.view_args)
  File "/usr/local/lib/python3.8/dist-packages/flask_classful.py", line 239, in inner
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/hiddifypanel/panel/user/user.py", line 42, in new
    c=get_common_data(g.user_uuid,mode="new")
  File "/usr/local/lib/python3.8/dist-packages/hiddifypanel/panel/user/user.py", line 219, in get_common_data
    "ip_debug":clean_ip.get_real_user_ip_debug()
  File "/usr/local/lib/python3.8/dist-packages/hiddifypanel/panel/clean_ip.py", line 55, in get_real_user_ip_debug
    asn = f"{asnres.get('autonomous_system_number','unknown')}" if asnres else "unknown"
AttributeError: 'str' object has no attribute 'get'

**Comment by NikanMirH** [comment]
منم دقیقا

**Comment by NikanMirH** [comment]
آپدیت کن اوکی میشه

**Comment by diakodfrr** [comment]
برای منم همینطور آپدیت خودکار انجام میشه برای من الان رو آخرین نسخه هستش مشکل از آپدیت جدید هستش لطفاً بررسی کنید
چطور میشه برگشت رو نسخه قبلی!

**Comment by aminamin1368** [comment]
منم این مشکل رو دارم

**Comment by HoMa431** [comment]
من دو تا کار انجام دادم گویا درست شد .
زبان پنل کاربری رو انگلیسی کردم ، آپدیت رو بصورت دستی زدم ..

**Comment by amin30000** [comment]
> من دو تا کار انجام دادم گویا درست شد . زبان پنل کاربری رو انگلیسی کردم ، آپدیت رو بصورت دستی زدم ..

کامند ای پی دستی رو میدی
