### ISSUE TITLE
ارور ۵۰۰ در صفحه اطلاعات مربوط به کانفیک ها برای کاربران

### ISSUE THREAD

**Issue by diakodfrr** [hiddify/hiddify-config#538]
سلام از صبح با ارور 500 در صفحه کاربران روبروشدم
500
Oops! Something went wrong. Hiddify Panel 2.7.3
Please contact hiddify@gmail.com with the details in this page.

The MaxMind DB file's search tree is corrupt
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/usr/local/lib/python3.10/dist-packages/flask_classful.py", line 268, in proxy
    response = view(**request.view_args)
  File "/usr/local/lib/python3.10/dist-packages/flask_classful.py", line 239, in inner
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/hiddifypanel/panel/user/user.py", line 42, in new
    c=get_common_data(g.user_uuid,mode="new")
  File "/usr/local/lib/python3.10/dist-packages/hiddifypanel/panel/user/user.py", line 219, in get_common_data
    "ip_debug":clean_ip.get_real_user_ip_debug()
  File "/usr/local/lib/python3.10/dist-packages/hiddifypanel/panel/clean_ip.py", line 54, in get_real_user_ip_debug
    asnres = ipasn.get(user_ip) if ipasn else {'autonomous_system_number':'unknown'}
  File "/usr/local/lib/python3.10/dist-packages/maxminddb/reader.py", line 120, in get
    (record, _) = self.get_with_prefix_len(ip_address)
  File "/usr/local/lib/python3.10/dist-packages/maxminddb/reader.py", line 151, in get_with_prefix_len
    return self._resolve_data_pointer(pointer), prefix_len
  File "/usr/local/lib/python3.10/dist-packages/maxminddb/reader.py", line 216, in _resolve_data_pointer
    raise InvalidDatabaseError("The MaxMind DB file's search tree is corrupt")
maxminddb.errors.InvalidDatabaseError: The MaxMind DB file's search tree is corrupt

**Comment by lymanjre** [comment]
آپدیت جدید را چک کنید لطفا. مشکی نداره
