### ISSUE TITLE
ERR_SSL_VERSION_OR_CIPHER_MISMATCH

### ISSUE THREAD

**Issue by alidehghan** [hiddify/hiddify-config#60]
hello,

after installing, this error appears in browser for using admin panel "ERR_SSL_VERSION_OR_CIPHER_MISMATCH"

**Comment by smf8** [comment]
I faced the similiar issue and wanted to provide additional context. 

This is because of `xray` panicing with stack trace:
```go
panic: runtime error: index out of range [175] with length 127

goroutine 19201025 [running]:
github.com/xtls/xray-core/common/strmatcher.(*ACAutomaton).Match(...)
	github.com/xtls/xray-core/common/strmatcher/ac_automaton_matcher.go:228
github.com/xtls/xray-core/common/strmatcher.(*MphMatcherGroup).Match(0xc000bf1cb0, {0xc006d02ac0, 0x8})
	github.com/xtls/xray-core/common/strmatcher/mph_matcher.go:186 +0x3a5
github.com/xtls/xray-core/app/router.(*DomainMatcher).ApplyDomain(0xc000bfd110, {0xc006d02a88?, 0xc0002df9f0?})
	github.com/xtls/xray-core/app/router/condition.go:102 +0x4a
github.com/xtls/xray-core/app/router.(*DomainMatcher).Apply(0xc000bd1620?, {0x1407e30?, 0xc006b31bc0?})
	github.com/xtls/xray-core/app/router/condition.go:111 +0x4d
github.com/xtls/xray-core/app/router.(*ConditionChan).Apply(0x8?, {0x1407e30, 0xc006b31bc0})
	github.com/xtls/xray-core/app/router/condition.go:32 +0x84
github.com/xtls/xray-core/app/router.(*Rule).Apply(...)
	github.com/xtls/xray-core/app/router/config.go:63
github.com/xtls/xray-core/app/router.(*Router).pickRouteInternal(0xc0001cf000, {0x1407ea0, 0xc0032e5c98})
	github.com/xtls/xray-core/app/router/router.go:94 +0x17d
github.com/xtls/xray-core/app/router.(*Router).PickRoute(0x13ff080?, {0x1407ea0?, 0xc0032e5c98?})
	github.com/xtls/xray-core/app/router/router.go:72 +0x27
github.com/xtls/xray-core/app/dispatcher.(*DefaultDispatcher).routedDispatch(0xc000bfa1e0, {0x13ff080, 0xc0092ba630?}, 0xc005086e00, {{0x1400af8?, 0xc0066196c0?}, 0x1?, 0x0?})
	github.com/xtls/xray-core/app/dispatcher/default.go:452 +0x30e
github.com/xtls/xray-core/app/dispatcher.(*DefaultDispatcher).Dispatch.func1()
	github.com/xtls/xray-core/app/dispatcher/default.go:323 +0x4c5
created by github.com/xtls/xray-core/app/dispatcher.(*DefaultDispatcher).Dispatch
	github.com/xtls/xray-core/app/dispatcher/default.go:304 +0x3dd
```

I dug a little but couldn't find a root cause. But with this even with `bash restart.sh` xray faces another problem:

```text
Failed to start: app/proxyman/inbound: failed to listen Unix Domain Socket on /dev/shm/hiddify-xtls-main.sock,0666 > transport/internet: failed to listen on unix address: /dev/shm/hiddify-xtls-main.sock,0666 > transport/internet/tcp: failed to listen Unix Domain Socket on /dev/shm/hiddify-xtls-main.sock,0666 > listen unix /dev/shm/hiddify-xtls-main.sock: bind: address already in use
```

Which requires `rm -rf /dev/shm/hiddify-xtls-main.sock*` before `bash restart.sh`.

**Comment by hiddify** [comment]
سلام
لطفا به ورژن جدید به روز رسانی کنید و نتیجه را اعلام کنید
با سپاس

**Comment by navidnadery** [comment]
https://developers.cloudflare.com/ssl/troubleshooting/version-cipher-mismatch/#certificate-activation

اول اینکه اگر از CDN استفاده می کنید حتما ssl اش رو full بزنید و دوم اینکه از یک لول سابدامنه استفاده کنید.
