### ISSUE TITLE
باگ قسمت کاربران در آپدیت ۳.۰.۳

### ISSUE THREAD

**Issue by mdseven** [hiddify/hiddify-config#610]
سلام 
با تشکر از آپدیت جدید و امکاناتی ک اضافه شده
توی آپدیت جدید قسمت کاربران هر تغییری اعمال شه(ساخت ویرایش و حذف یوذر) ارور 502 Bad Gateway ظاهر میشه
تغییرات ولی اعمال میشه
ولی خب باید هی بک بزنی بیای صفحه کابران بری صفحه اخر یوذری ک ساختی ببینی
این مسئله موقع ساخت چند اکانت پشت هم که خیلی اذیت کنندس

**Comment by amin30000** [comment]
برای من هم این مشکل بود بهش انقدر ور رفتم که کلا کل سرورم دان شده و دیگه بالا نمیاد و ارور دریافت میکنم

**Comment by pourmina** [comment]
وقتی وارد پنل کاربران میشم این ارور میاد
500
خطایی رخ داده است!! Hiddify Panel 3.0.3
لطفا با هیدیفای از طریق آدرس ایمیل hiddify@gmail.com و ذکر مشخصات این صفحه در ارتباط باشید.
argument of type 'NoneType' is not iterable
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/usr/local/lib/python3.10/dist-packages/flask_admin/base.py", line 69, in inner
    return self._run_view(f, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/flask_admin/base.py", line 368, in _run_view
    return fn(self, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/flask_admin/model/base.py", line 2017, in index_view
    return self.render(
  File "/usr/local/lib/python3.10/dist-packages/flask_admin/base.py", line 308, in render
    return render_template(template, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/flask/templating.py", line 154, in render_template
    return _render(
  File "/usr/local/lib/python3.10/dist-packages/flask/templating.py", line 128, in _render
    rv = template.render(context)
  File "/usr/local/lib/python3.10/dist-packages/jinja2/environment.py", line 1301, in render self.environment.handle_exception()
  File "/usr/local/lib/python3.10/dist-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/usr/local/lib/python3.10/dist-packages/hiddifypanel/panel/admin/templates/model/user_list.html", line 1, in top-level template code
    {% extends 'hiddify-flask-admin/list.html' %}
  File "/usr/local/lib/python3.10/dist-packages/hiddifypanel/templates/hiddify-flask-admin/list.html", line 6, in top-level template code
    {% import 'flask-admin/model/row_actions.html' as row_actions with context %}
  File "/usr/local/lib/python3.10/dist-packages/flask_adminlte3/templates/flask-admin/master.html", line 1, in top-level template code
    {% extends admin_base_template %}
  File "/usr/local/lib/python3.10/dist-packages/hiddifypanel/templates/flaskadmin-layout.html", line 1, in top-level template code
    {% extends 'admin-layout.html' %}
  File "/usr/local/lib/python3.10/dist-packages/hiddifypanel/templates/admin-layout.html", line 2, in top-level template code
    {% from 'macros.html' import icon,render_nav_item %}
  File "/usr/local/lib/python3.10/dist-packages/hiddifypanel/templates/master.html", line 71, in top-level template code
    {% block page_body %}
  File "/usr/local/lib/python3.10/dist-packages/hiddifypanel/templates/master.html", line 103, in block 'page_body'
    {% block body %}{% endblock %}
  File "/usr/local/lib/python3.10/dist-packages/hiddifypanel/panel/admin/templates/model/user_list.html", line 4, in block 'body'
    {{super()}}
  File "/usr/local/lib/python3.10/dist-packages/hiddifypanel/templates/hiddify-flask-admin/list.html", line 78, in block 'body'
    {% block model_list_table %}
  File "/usr/local/lib/python3.10/dist-packages/hiddifypanel/templates/hiddify-flask-admin/list.html", line 129, in block 'model_list_table'
    {% block list_row scoped %}
  File "/usr/local/lib/python3.10/dist-packages/hiddifypanel/templates/hiddify-flask-admin/list.html", line 158, in block 'list_row'
    {{ get_value(row, c) }}
  File "/usr/local/lib/python3.10/dist-packages/flask_admin/model/base.py", line 1865, in get_list_value
    return self._get_list_value(
  File "/usr/local/lib/python3.10/dist-packages/flask_admin/model/base.py", line 1835, in _get_list_value
    value = column_fmt(self, context, model, name)
  File "/usr/local/lib/python3.10/dist-packages/hiddifypanel/panel/admin/UserAdmin.py", line 126, in _ul_formatter
    return Markup(" ".join([hiddify.get_user_link(model.uuid,d,'new',model.name) for d in domains]))
  File "/usr/local/lib/python3.10/dist-packages/hiddifypanel/panel/admin/UserAdmin.py", line 126, in <listcomp>
    return Markup(" ".join([hiddify.get_user_link(model.uuid,d,'new',model.name) for d in domains]))
  File "/usr/local/lib/python3.10/dist-packages/hiddifypanel/panel/hiddify.py", line 234, in get_user_link auto_cdn=(domain.mode==DomainType.auto_cdn_ip) or ("MTN" in domain.cdn_ip)
TypeError: argument of type 'NoneType' is not iterable

**Comment by amin30000** [comment]
برای من هم این ارور رو میده 

خطایی رخ داده است!! Hiddify Panel 3.0.3
لطفا با هیدیفای از طریق آدرس ایمیل hiddify@gmail.com و ذکر مشخصات این صفحه در ارتباط باشید.

        
argument of type 'NoneType' is not iterable
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/usr/local/lib/python3.10/dist-packages/flask_admin/base.py", line 69, in inner
    return self._run_view(f, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/flask_admin/base.py", line 368, in _run_view
    return fn(self, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/flask_admin/model/base.py", line 2017, in index_view
    return self.render(
  File "/usr/local/lib/python3.10/dist-packages/flask_admin/base.py", line 308, in render
    return render_template(template, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/flask/templating.py", line 154, in render_template
    return _render(
  File "/usr/local/lib/python3.10/dist-packages/flask/templating.py", line 128, in _render
    rv = template.render(context)
  File "/usr/local/lib/python3.10/dist-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/usr/local/lib/python3.10/dist-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/usr/local/lib/python3.10/dist-packages/hiddifypanel/panel/admin/templates/model/user_list.html", line 1, in top-level template code
    {% extends 'hiddify-flask-admin/list.html' %}
  File "/usr/local/lib/python3.10/dist-packages/hiddifypanel/templates/hiddify-flask-admin/list.html", line 6, in top-level template code
    {% import 'flask-admin/model/row_actions.html' as row_actions with context %}
  File "/usr/local/lib/python3.10/dist-packages/flask_adminlte3/templates/flask-admin/master.html", line 1, in top-level template code
    {% extends admin_base_template %}
  File "/usr/local/lib/python3.10/dist-packages/hiddifypanel/templates/flaskadmin-layout.html", line 1, in top-level template code
    {% extends 'admin-layout.html' %}
  File "/usr/local/lib/python3.10/dist-packages/hiddifypanel/templates/admin-layout.html", line 2, in top-level template code
    {% from 'macros.html' import icon,render_nav_item %}
  File "/usr/local/lib/python3.10/dist-packages/hiddifypanel/templates/master.html", line 71, in top-level template code
    {% block page_body %}
  File "/usr/local/lib/python3.10/dist-packages/hiddifypanel/templates/master.html", line 103, in block 'page_body'
    {% block body %}{% endblock %}
  File "/usr/local/lib/python3.10/dist-packages/hiddifypanel/panel/admin/templates/model/user_list.html", line 4, in block 'body'
    {{super()}}
  File "/usr/local/lib/python3.10/dist-packages/hiddifypanel/templates/hiddify-flask-admin/list.html", line 78, in block 'body'
    {% block model_list_table %}
  File "/usr/local/lib/python3.10/dist-packages/hiddifypanel/templates/hiddify-flask-admin/list.html", line 129, in block 'model_list_table'
    {% block list_row scoped %}
  File "/usr/local/lib/python3.10/dist-packages/hiddifypanel/templates/hiddify-flask-admin/list.html", line 158, in block 'list_row'
    {{ get_value(row, c) }}
  File "/usr/local/lib/python3.10/dist-packages/flask_admin/model/base.py", line 1865, in get_list_value
    return self._get_list_value(
  File "/usr/local/lib/python3.10/dist-packages/flask_admin/model/base.py", line 1835, in _get_list_value
    value = column_fmt(self, context, model, name)
  File "/usr/local/lib/python3.10/dist-packages/hiddifypanel/panel/admin/UserAdmin.py", line 126, in _ul_formatter
    return Markup(" ".join([hiddify.get_user_link(model.uuid,d,'new',model.name) for d in domains]))
  File "/usr/local/lib/python3.10/dist-packages/hiddifypanel/panel/admin/UserAdmin.py", line 126, in <listcomp>
    return Markup(" ".join([hiddify.get_user_link(model.uuid,d,'new',model.name) for d in domains]))
  File "/usr/local/lib/python3.10/dist-packages/hiddifypanel/panel/hiddify.py", line 234, in get_user_link
    auto_cdn=(domain.mode==DomainType.auto_cdn_ip) or ("MTN" in domain.cdn_ip)
TypeError: argument of type 'NoneType' is not iterable

**Comment by hiddify1** [comment]
fixed

**Comment by mdseven** [comment]
> fixed

توی آپدیت ۳.۰.۸ حل شده بود
ولی توی ۳.۰.۹ مجدد این باگ برگشته
