### ISSUE TITLE
"name 'hconfig' is not defined" error for user link

### ISSUE THREAD

**Issue by thawri1** [hiddify/hiddify-config#93]
user link return this error:
name 'hconfig' is not defined
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/usr/local/lib/python3.8/dist-packages/flask_classful.py", line 268, in proxy
    response = view(**request.view_args)
  File "/usr/local/lib/python3.8/dist-packages/flask_classful.py", line 239, in inner
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/hiddifypanel/panel/user/user.py", line 15, in index
    c=get_common_data(g.user_uuid)
  File "/usr/local/lib/python3.8/dist-packages/hiddifypanel/panel/user/user.py", line 78, in get_common_data
    g.cdn_forced_host=hconfig(ConfigEnum.cdn_forced_host) or domain
NameError: name 'hconfig' is not defined

**Comment by aliazimoshan** [comment]
I have the same issue

**Comment by thawri1** [comment]
hetzner, ubuntu 20.04

**Comment by thawri1** [comment]
> hetzner, ubuntu 20.04

no problem on 22.04

**Comment by aliazimoshan** [comment]
It works with CDN configuration.

**Comment by hiddify** [comment]
Fixed
